// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SKShopAPI.DataAccess;

namespace SKShopAPI.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20220522173158_sample-products-data-added")]
    partial class sampleproductsdataadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "82659aa3-4b78-477b-9cd1-d03e2cc4f7b1",
                            ConcurrencyStamp = "b38bfa04-3fd9-49a0-8f67-0a4002831669",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "7f41c946-b546-45fe-8ad0-6e8575a4c5f9",
                            ConcurrencyStamp = "aa624519-7212-42ee-8ace-fbb18e66965e",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SKShopAPI.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DateAdded")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductAmountAvailable")
                        .HasColumnType("int");

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ProductDiscount")
                        .HasColumnType("decimal(1,1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductImgUrl")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("ProductIsInstock")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("357fb7c4-b49a-4b78-90fe-08d9c009e093"),
                            Description = "Fine bracelets for men",
                            Name = "Men"
                        },
                        new
                        {
                            Id = new Guid("aa920d5c-d44e-4d5c-90ff-08d9c009e093"),
                            Description = "Bracelets for sports",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("0bbc8cb9-cc68-4c16-90fc-08d9c009e093"),
                            Description = "Fashion and Designer watches",
                            Name = "Watches"
                        },
                        new
                        {
                            Id = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Description = "Fashion and Designer bracelets for women",
                            Name = "Women"
                        });
                });

            modelBuilder.Entity("SKShopAPI.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountAvailable")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DateCreated")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(1,1)");

                    b.Property<string>("ImgName")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsHot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInstock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItemOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a671375-5c8b-447e-8b41-97f0742ba671"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/1.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("85f8d933-14b5-43a5-8151-451d5bd2bf91"),
                            AmountAvailable = 76,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/2.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("be27e401-656a-46a8-bf19-558642a87615"),
                            AmountAvailable = 34,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/3.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("c1c78615-1559-4232-9dc3-dbcd6b33bbfe"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/4.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("63feb0db-b5ec-47af-8bae-0a491e33745e"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/5.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("91991041-7c9b-4715-bcdb-8b165463cd4d"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/6.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("24437a2d-9251-4b5e-8b47-fe5ed6be6df2"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/7.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("18443c2f-2a73-433d-b07c-bec676fd54d1"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/8.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("04ff1fa6-223b-44c7-9bb0-218373a61451"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/9.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("849d47dc-4dff-4ed8-a7a7-f19d6d57f0f9"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/10.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("abdb59ca-6286-4668-8552-96fde7910b0d"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/11.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("a046e148-e09b-4c31-abd1-49c34df63ab4"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/12.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("5212ade5-7a04-4947-ac0f-7f04338940fe"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/13.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("7af2bc9a-de1b-4f85-a60a-954d30e14513"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/14.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("e18f417a-2497-49e4-bb14-9855384f9440"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/15.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("b6cf0e5a-9e1e-4324-9487-04334ee5d976"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/16.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("016d621f-dbb9-4d30-97e5-c67d1df7006d"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/17.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("9785bd88-bbd6-4194-909a-b25ec950f52c"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/18.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("4bc4343b-4be0-4d87-9159-c057c6e25881"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/19.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("438527f9-6330-4699-83a9-3294e743952e"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/20.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("0b9cd94c-28c2-4e15-8f7e-76eee6bcd282"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/21.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("4aab3acb-231f-4c8b-bbf4-4c4c4a354d82"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/22.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("bc1ce0d7-92a4-4b03-88a9-470ad38f7679"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/23.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("bec06195-7f2c-4432-a076-418be31f340d"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/24.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("ea9462f0-d63d-460e-92a2-781c9458eec0"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/25.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("ce507147-d191-4c0c-aa1c-c72f7f52edab"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/26.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("9bf390da-09d2-4e3d-b134-fc551d88b3ed"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/27.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("2a78eaae-7519-42d3-91ef-650342766917"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/28.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("91e620ea-7ce0-49ed-9470-a40a7887ade2"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/29.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("3424d726-9737-46b3-af70-79e07da5f592"),
                            AmountAvailable = 108,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sun, 22 May 2022 17:31:57 GMT",
                            Discount = 0.1m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/30.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        });
                });

            modelBuilder.Entity("SKShopAPI.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ImgName")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RegisterDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SKShopAPI.Entities.CartItem", b =>
                {
                    b.HasOne("SKShopAPI.Entities.Order", null)
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Order", b =>
                {
                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Product", b =>
                {
                    b.HasOne("SKShopAPI.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Order", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SKShopAPI.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
