// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SKShopAPI.DataAccess;

namespace SKShopAPI.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20220528000943_more_initial_products_added")]
    partial class more_initial_products_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "94ae6d62-c563-42d0-906b-a45c7b8966eb",
                            ConcurrencyStamp = "52b6c560-306c-4742-8156-db317ea5fe9e",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "3e6f226d-045f-42f0-9938-90fc167ff379",
                            ConcurrencyStamp = "bb7312fa-dead-4109-abfc-e76cfa26b804",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SKShopAPI.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DateAdded")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductAmountAvailable")
                        .HasColumnType("int");

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ProductDiscount")
                        .HasColumnType("decimal(1,1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductImgUrl")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("ProductIsInstock")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("357fb7c4-b49a-4b78-90fe-08d9c009e093"),
                            Description = "Fashion and Designers for men",
                            Name = "Men"
                        },
                        new
                        {
                            Id = new Guid("aa920d5c-d44e-4d5c-90ff-08d9c009e093"),
                            Description = "Products for sports",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("0bbc8cb9-cc68-4c16-90fc-08d9c009e093"),
                            Description = "Fashion and Designer for Young People",
                            Name = "Young"
                        },
                        new
                        {
                            Id = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Description = "Fashion and Designers for women",
                            Name = "Women"
                        },
                        new
                        {
                            Id = new Guid("2868642b-8c0a-44ec-00fd-43d9c009e126"),
                            Description = "Latest Quality Gadgets",
                            Name = "Gadgets"
                        });
                });

            modelBuilder.Entity("SKShopAPI.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountAvailable")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DateCreated")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(1,1)");

                    b.Property<string>("ImgName")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsHot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInstock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItemOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5a1bba2-b431-44d2-9aab-1c99b98cff7c"),
                            AmountAvailable = 150,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Blue",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.3m,
                            ImgName = "1.jpg",
                            ImgUrl = "https://localhost:5001/img/1.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Sk Duoyo Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("f79e4a2b-e664-4cd1-a3c2-f6245c43efed"),
                            AmountAvailable = 763,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "2.jpg",
                            ImgUrl = "https://localhost:5001/img/2.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Golden Chain Bracelet",
                            Price = 15.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("7b30f49b-d015-43cd-833f-d52f46bc4175"),
                            AmountAvailable = 34,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Dark",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.1m,
                            ImgName = "3.jpg",
                            ImgUrl = "https://localhost:5001/img/3.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Dark Wooven Bracelet",
                            Price = 89.98m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("58e507b9-0598-4b27-937a-90e15e4fd297"),
                            AmountAvailable = 786,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Blue",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "4.jpg",
                            ImgUrl = "https://localhost:5001/img/4.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Blue Chain Bracelet",
                            Price = 199.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("0bbf2fa3-f001-4fa9-8009-0ed5320a7956"),
                            AmountAvailable = 560,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Red",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.15m,
                            ImgName = "5.jpg",
                            ImgUrl = "https://localhost:5001/img/5.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Casual Love Women Bracelet",
                            Price = 96.50m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("5c92ad2f-06c1-40c2-8c7e-43385d3a37af"),
                            AmountAvailable = 235,
                            CategoryId = new Guid("357fb7c4-b49a-4b78-90fe-08d9c009e093"),
                            Color = "Blue",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.3m,
                            ImgName = "6.jpg",
                            ImgUrl = "https://localhost:5001/img/6.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Men Wrist Bracelet",
                            Price = 45.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("5568b375-5296-41cb-8da8-71f952644132"),
                            AmountAvailable = 264,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "7.jpg",
                            ImgUrl = "https://localhost:5001/img/7.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "CK Pink",
                            Price = 39.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("7b7eb870-4168-46a5-8c8e-8d77a631c2b9"),
                            AmountAvailable = 900,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Black",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.1m,
                            ImgName = "8.jpg",
                            ImgUrl = "https://localhost:5001/img/8.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Black Butter-Fly",
                            Price = 370.95m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("ad74ac6e-1ba0-4931-a065-12c761d1601b"),
                            AmountAvailable = 209,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.1m,
                            ImgName = "9.jpg",
                            ImgUrl = "https://localhost:5001/img/9.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Pink Chain Bracelet",
                            Price = 56.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("cd48196a-c4ab-44ce-8ef6-21e67bedc7a4"),
                            AmountAvailable = 450,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Yellow",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "10.jpg",
                            ImgUrl = "https://localhost:5001/img/10.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Golden Amulate",
                            Price = 78.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("d3aff2f8-4951-4a5c-a382-d417365dfb1d"),
                            AmountAvailable = 832,
                            CategoryId = new Guid("357fb7c4-b49a-4b78-90fe-08d9c009e093"),
                            Color = "Red",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.1m,
                            ImgName = "11.jpg",
                            ImgUrl = "https://localhost:5001/img/11.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Men Rhinestone",
                            Price = 23.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("767bb381-f535-4d43-b87d-b97730b53a4a"),
                            AmountAvailable = 345,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Yellow",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "12.jpg",
                            ImgUrl = "https://localhost:5001/img/12.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Yellow Love",
                            Price = 99.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("3b13a409-4421-4ddc-90dd-82387d2f254b"),
                            AmountAvailable = 543,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Red",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.15m,
                            ImgName = "13.jpg",
                            ImgUrl = "https://localhost:5001/img/13.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Red Butterfly Bracelet",
                            Price = 199.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("8a28435a-f452-4f5a-a37f-bd446e263ded"),
                            AmountAvailable = 890,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Yellow",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "14.jpg",
                            ImgUrl = "https://localhost:5001/img/14.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Yellowish Butterfly Bracelet",
                            Price = 86.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("35086945-8527-4ee9-8f40-f267928563d0"),
                            AmountAvailable = 564,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Green",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "15.jpg",
                            ImgUrl = "https://localhost:5001/img/15.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Green Local Weave Bracelet",
                            Price = 156.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("4326175e-654c-4b59-8639-cce104098fd3"),
                            AmountAvailable = 183,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Red",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "16.jpg",
                            ImgUrl = "https://localhost:5001/img/16.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Red Local Weave Bracelet",
                            Price = 73.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("afacfdc4-302a-470e-bbe5-c6c28147a50c"),
                            AmountAvailable = 674,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Gray",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "17.jpg",
                            ImgUrl = "https://localhost:5001/img/17.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Gray Chain Bracelet",
                            Price = 109.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("01ca406b-4a58-4fa5-b8c4-2fae4d0dc5c5"),
                            AmountAvailable = 725,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Gold",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "18.jpg",
                            ImgUrl = "https://localhost:5001/img/18.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Golden Star Love Bracete",
                            Price = 130.98m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("6c8040ce-4e5c-452e-b476-e046cbcf0489"),
                            AmountAvailable = 363,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Pink",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "19.jpg",
                            ImgUrl = "https://localhost:5001/img/19.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Light Pink Star Love Bracete",
                            Price = 105.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("682c2f5b-7ae4-49fb-9d8f-adf222302174"),
                            AmountAvailable = 122,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Green",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.1m,
                            ImgName = "20.jpg",
                            ImgUrl = "https://localhost:5001/img/20.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Rhinestones Duoya Bracelet Watch",
                            Price = 110.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("6094ed7d-2642-4c71-b72c-260af4a9b059"),
                            AmountAvailable = 323,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Silver",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.13m,
                            ImgName = "21.jpg",
                            ImgUrl = "https://localhost:5001/img/21.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Fan Teeda Love Bracelet",
                            Price = 166.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("ea9c0fd4-b526-4661-a602-d78616322673"),
                            AmountAvailable = 98,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Brown",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "22.jpg",
                            ImgUrl = "https://localhost:5001/img/22.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Blood Red Duoya Bracelet",
                            Price = 96.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("0922c952-8fc6-4ac3-8e39-7c4ffd6bd08d"),
                            AmountAvailable = 160,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Green",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.1m,
                            ImgName = "23.jpg",
                            ImgUrl = "https://localhost:5001/img/23.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Green Duoya Chain Bracelet",
                            Price = 77.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("e37d247b-6b79-49da-a1ca-1c3679d2f9af"),
                            AmountAvailable = 675,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Red",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "24.jpg",
                            ImgUrl = "https://localhost:5001/img/24.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Red Duoya Chain Bracelet",
                            Price = 89.97m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("43795276-ba28-4b0a-8b50-ad8fbf71e4ba"),
                            AmountAvailable = 59,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Silver",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "25.jpg",
                            ImgUrl = "https://localhost:5001/img/25.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Fan Teeda Silver Rhinestone Bracelet",
                            Price = 259.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("e19f9012-2dab-4627-b1d4-abeacf4f02f7"),
                            AmountAvailable = 800,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Red",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "26.jpg",
                            ImgUrl = "https://localhost:5001/img/26.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Fan Teeda Red Rhinestone Bracelet",
                            Price = 278.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("ed6da7cb-f541-478e-954e-e04625a17165"),
                            AmountAvailable = 198,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Red",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.1m,
                            ImgName = "27.jpg",
                            ImgUrl = "https://localhost:5001/img/27.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Fan Teeda Blood Red Rhinestone Bracelet",
                            Price = 199.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("06c43706-c835-425d-8db6-893f5857e927"),
                            AmountAvailable = 698,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "Gray",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "28.jpg",
                            ImgUrl = "https://localhost:5001/img/28.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Fan Teeda Gray Rhinestone Bracelet",
                            Price = 200.00m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("9e8807be-f6d9-4ec5-926f-bc61f59e0151"),
                            AmountAvailable = 98,
                            CategoryId = new Guid("2868642b-8c0a-44ec-00fd-43d9c009e126"),
                            Color = "Brown",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.9m,
                            ImgName = "29.jpg",
                            ImgUrl = "https://localhost:5001/img/29.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Brown Smart Watch",
                            Price = 569.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("72d54e6d-6f15-45ca-9f50-756f64abed77"),
                            AmountAvailable = 378,
                            CategoryId = new Guid("2868642b-8c0a-44ec-00fd-43d9c009e126"),
                            Color = "Silver",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.9m,
                            ImgName = "30.jpg",
                            ImgUrl = "https://localhost:5001/img/30.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "AZ Pentom Laptop",
                            Price = 2499.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("1806e1e6-f3ac-4c16-86ce-842355bcf971"),
                            AmountAvailable = 198,
                            CategoryId = new Guid("2868642b-8c0a-44ec-00fd-43d9c009e126"),
                            Color = "White",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0.3m,
                            ImgName = "31.jpg",
                            ImgUrl = "https://localhost:5001/img/31.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "White Smart Watch",
                            Price = 899.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("6c38829d-dea7-4cd0-9bbc-54456a7f9d8e"),
                            AmountAvailable = 38,
                            CategoryId = new Guid("2868642b-8c0a-44ec-00fd-43d9c009e126"),
                            Color = "Gray",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "32.jpg",
                            ImgUrl = "https://localhost:5001/img/32.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Slick Design Dake PC Laptop",
                            Price = 2999.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("c8ef4c35-afa3-4ecc-bd7d-e633fbc70fa7"),
                            AmountAvailable = 388,
                            CategoryId = new Guid("2868642b-8c0a-44ec-00fd-43d9c009e126"),
                            Color = "Gray",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "33.jpg",
                            ImgUrl = "https://localhost:5001/img/33.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "GLK 300 Android Phone",
                            Price = 999.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("72f9bac4-136e-4a64-815d-e4361517830d"),
                            AmountAvailable = 218,
                            CategoryId = new Guid("357fb7c4-b49a-4b78-90fe-08d9c009e093"),
                            Color = "Red",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "34.jpg",
                            ImgUrl = "https://localhost:5001/img/34.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "Red T-Shirt for men",
                            Price = 49.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("b83d25dd-1340-4e03-b9b7-12ed2bcfb328"),
                            AmountAvailable = 618,
                            CategoryId = new Guid("0bbc8cb9-cc68-4c16-90fc-08d9c009e093"),
                            Color = "White",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "35.jpg",
                            ImgUrl = "https://localhost:5001/img/35.jpg",
                            IsHot = true,
                            IsInstock = true,
                            IsItemOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "White T-Shirt for Young",
                            Price = 29.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        },
                        new
                        {
                            Id = new Guid("efb817a1-eb23-4c5f-864a-400652d68c49"),
                            AmountAvailable = 918,
                            CategoryId = new Guid("e931604b-8cba-41ec-90fd-08d9c009e093"),
                            Color = "White",
                            DateCreated = "Sat, 28 May 2022 00:09:42 GMT",
                            Discount = 0m,
                            ImgName = "36.jpg",
                            ImgUrl = "https://localhost:5001/img/36.jpg",
                            IsHot = false,
                            IsInstock = true,
                            IsItemOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt vero, sit saepe temporibus veritatis quod tempore qui at maxime hic animi ipsa illum dolor optio suscipit quas aliquam ab repudiandae. Incidunt exercitationem minima illum autem officiis suscipit quo esse perferendis consectetur ipsa. Perspiciatis exercitationem a eos sit, qui id veritatis!",
                            Name = "White T-Shirt for Women",
                            Price = 69.99m,
                            ShortDescription = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dignissimos veniam id recusandae nemo? Nostrum?"
                        });
                });

            modelBuilder.Entity("SKShopAPI.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ImgName")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RegisterDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SKShopAPI.Entities.CartItem", b =>
                {
                    b.HasOne("SKShopAPI.Entities.Order", null)
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Order", b =>
                {
                    b.HasOne("SKShopAPI.Entities.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Product", b =>
                {
                    b.HasOne("SKShopAPI.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SKShopAPI.Entities.Order", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SKShopAPI.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
